name: Commit Lint

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, edited]

jobs:
  commit-lint:
    name: commit-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Commit Lint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .github/commitlint.config.js
